name: Build and Deploy to GKE

on:
  push:
    branches:
      - master

defaults: # default working directory for all run jobs
  run:
    shell: bash
    working-directory: k8s/cloud_cluster/gcp

env:
  TERRAFORM_VERSION: 1.0.9

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
    
    - name: Create gcp credentials
      run: |-
        echo $sa > secret/sa.json
        cat > secret/gcs.tfvars <<EOF
        credentials = "secret/sa.json"
        bucket = "$bucket"
        prefix = "$prefix"
        EOF
        cat secret/gcs.tfvars
      env:
        bucket: ${{ secrets.BUCKET }}
        prefix: ${{ secrets.PREFIX }}
        sa: ${{ secrets.SA }}

    - name: Run terraform init
      run: terraform init -backend-config=secret/gcs.tfvars -reconfigure

    - name: Run terraform plan
      run: terraform plan -var-file=vars.tfvars -out=secret/tfplan

    - name: Run terraform apply
      run: terraform apply secret/tfplan

